/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspectsRouteImport } from './routes/suspects'
import { Route as ReportRouteImport } from './routes/report'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FingerprintRouteImport } from './routes/fingerprint'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SuspectsRoute = SuspectsRouteImport.update({
  id: '/suspects',
  path: '/suspects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintRoute = FingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/cases': typeof CasesRoute
  '/dna': typeof DnaRoute
  '/evidence': typeof EvidenceRoute
  '/fingerprint': typeof FingerprintRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/report': typeof ReportRoute
  '/suspects': typeof SuspectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/cases': typeof CasesRoute
  '/dna': typeof DnaRoute
  '/evidence': typeof EvidenceRoute
  '/fingerprint': typeof FingerprintRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/report': typeof ReportRoute
  '/suspects': typeof SuspectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/cases': typeof CasesRoute
  '/dna': typeof DnaRoute
  '/evidence': typeof EvidenceRoute
  '/fingerprint': typeof FingerprintRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/report': typeof ReportRoute
  '/suspects': typeof SuspectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/assistant'
    | '/cases'
    | '/dna'
    | '/evidence'
    | '/fingerprint'
    | '/login'
    | '/notes'
    | '/report'
    | '/suspects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analysis'
    | '/assistant'
    | '/cases'
    | '/dna'
    | '/evidence'
    | '/fingerprint'
    | '/login'
    | '/notes'
    | '/report'
    | '/suspects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/assistant'
    | '/cases'
    | '/dna'
    | '/evidence'
    | '/fingerprint'
    | '/login'
    | '/notes'
    | '/report'
    | '/suspects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRoute
  AssistantRoute: typeof AssistantRoute
  CasesRoute: typeof CasesRoute
  DnaRoute: typeof DnaRoute
  EvidenceRoute: typeof EvidenceRoute
  FingerprintRoute: typeof FingerprintRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  ReportRoute: typeof ReportRoute
  SuspectsRoute: typeof SuspectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspects': {
      id: '/suspects'
      path: '/suspects'
      fullPath: '/suspects'
      preLoaderRoute: typeof SuspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprint': {
      id: '/fingerprint'
      path: '/fingerprint'
      fullPath: '/fingerprint'
      preLoaderRoute: typeof FingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRoute,
  AssistantRoute: AssistantRoute,
  CasesRoute: CasesRoute,
  DnaRoute: DnaRoute,
  EvidenceRoute: EvidenceRoute,
  FingerprintRoute: FingerprintRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  ReportRoute: ReportRoute,
  SuspectsRoute: SuspectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
